#!/bin/sh
#    51-wsl-motd-news - print the live news from the Ubuntu WSL.
#    Copyright (C) 2020 Canonical Ltd.
#    Copyright (C) 2020 Patrick Wu
#
#    Authors: Patrick Wu <patrick.wu@canonical.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://www.gnu.org/licenses/>.
#  
#  On Debian systems, the complete text of the GNU General
#  Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

# Source the local configuration
[ -f "/etc/ubuntu-wsl.conf" ] && . /etc/ubuntu-wsl.conf

# Exit immediately unless we're enabled
[ "$UBUNTU_WSL_MOTD_NEWS_ENABLED" = "true" ] || exit 0

# placeholder after confirm how should this part be implemented
CONTENT="This is a test news print for Ubuntu WSL."
printf  "%s\n" "$CONTENT" 

exit 0