#!/bin/bash
#    51-wsl-motd-news - print the live news from the Ubuntu WSL.
#    Copyright (C) 2020 Canonical Ltd.
#    Copyright (C) 2020 Patrick Wu
#
#    Authors: Patrick Wu <patrick.wu@canonical.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This package is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://www.gnu.org/licenses/>.
#  
#  On Debian systems, the complete text of the GNU General
#  Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".

# Source the local configuration
CUR_CONF_LOC=/etc/default/ubuntu-wsl/ubuntu-wsl.conf
[ -f "/etc/ubuntu-wsl.conf" ] && CUR_CONF_LOC=/etc/ubuntu-wsl.conf

__ubuntu_wsl_conf_handling() {
    section=""
    while IFS='=' read var val
    do
        if [[ $var =~ ^\;.*$ ]] || [[ $var =~ ^\#.*$ ]]
        then
            continue
        elif [[ $var =~ ^\[.*\]$ ]]
        then
            section="$(echo $var | tr -d '\[\]' | tr '[:lower:]' '[:upper:]')"
        elif [[ -n "$val" ]]
        then
            var="$(echo $var | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')"
            val="$(echo $val | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
            declare -r -g UBUNTU_WSL_${section}_${var}=${val}
        fi
    done < $CUR_CONF_LOC
}

[ -f "$CUR_CONF_LOC" ] && __ubuntu_wsl_conf_handling

# Exit immediately unless we're enabled
[ "$UBUNTU_WSL_MOTD_WSLNEWSENABLED" = "true" ] || exit 0

cat <<EOF
* Get support for Ubuntu on Windows Subsystem for Linux 2.
  Find out how Canonical can help you with x, y, z support for Ubuntu on WSL.

  http://www.ubuntu.com/wsl
EOF

exit 0